# Generated by Django 4.2.7 on 2023-11-13 06:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import source.base.service


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("club_service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="club_head",
        ),
        migrations.RemoveField(
            model_name="clubpost",
            name="user",
        ),
        migrations.AddField(
            model_name="clubpost",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    ),
                    source.base.service.validate_size_image,
                ],
            ),
        ),
        migrations.AddField(
            model_name="clubpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="club_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/club_logo/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpeg", "jpg"]
                    ),
                    source.base.service.validate_size_image,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="clubnews",
            name="content",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="clubpost",
            name="content",
            field=models.TextField(max_length=2000),
        ),
        migrations.CreateModel(
            name="ClubHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club",
                        to="club_service.club",
                    ),
                ),
                (
                    "club_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="head",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clubpost",
            name="poster",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="poster",
                to="club_service.clubhead",
            ),
            preserve_default=False,
        ),
    ]
