# Generated by Django 4.2.7 on 2023-11-13 10:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import source.base.service


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("club_service", "0002_remove_club_club_head_remove_clubpost_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="club_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clubs/club_logos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpeg", "jpg"]
                    ),
                    source.base.service.validate_size_image,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="club_members",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="clubhead",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="club_service.club"
            ),
        ),
        migrations.AlterField(
            model_name="clubhead",
            name="club_head",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="clubpost",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="clubs/club_posts/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    ),
                    source.base.service.validate_size_image,
                ],
            ),
        ),
        migrations.CreateModel(
            name="ClubStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank_in_club",
                    models.CharField(
                        choices=[
                            ("STAFF", "Junior Staff"),
                            ("PR", "Mobilograph"),
                            ("HR", "HR Specialist"),
                            ("VH", "Vice Head"),
                        ],
                        default="STAFF",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club",
                        to="club_service.club",
                    ),
                ),
                ("staff_user", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
