# Generated by Django 4.2.7 on 2023-11-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club_service", "0005_remove_club_club_members_club_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
