# Generated by Django 4.2.7 on 2023-11-15 08:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("club_service", "0006_club_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="club_name", unique=True
            ),
        ),
    ]
