# Generated by Django 4.2.7 on 2023-11-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club_service", "0007_alter_club_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
