# Generated by Django 4.2.7 on 2023-11-05 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator("That email can’t be used")
                ],
                verbose_name="Email Address",
            ),
        ),
    ]
