# Generated by Django 4.2.7 on 2023-11-10 17:42

import django.core.validators
from django.db import migrations, models
import source.base.service


class Migration(migrations.Migration):
    dependencies = [
        ("auth_service", "0003_onetimepassworduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    ),
                    source.base.service.validate_size_image,
                ],
            ),
        ),
    ]
